### ISSUE TITLE
Add support for Amazon's StarCluster as a backend

### ISSUE THREAD

**Issue by Sonictherocketman** [TorkamaniLab/metapipe#37]
The cluster environment is very similar to a Torque/PBS system, so creating a new subclass of the PBSJob and tweaking it slightly will suffice.

**Comment by Sonictherocketman** [comment]
Attempted execution of Metapipe in the default AWS environment resulted in this:

```bash
Python version 2.7.4

root@master:~/gadget-pipeline# metapipe -j sge -o pipe.sh pipeline.mp 
Traceback (most recent call last):
  File "/usr/local/bin/metapipe", line 9, in <module>
    load_entry_point('metapipe==1.2-0', 'console_scripts', 'metapipe')()
  File "/usr/local/lib/python2.7/dist-packages/metapipe/app.py", line 66, in main
    command_templates = parser.consume()
  File "/usr/local/lib/python2.7/dist-packages/metapipe/parser.py", line 22, in consume
    lowered = { key.lower(): val for key, val in first_pass.iteritems() }
TypeError: 'str' object is not callable
```
